### ISSUE TITLE
Allow bind/connect to be reversed among publishers and subscribers

### ISSUE THREAD

**Issue by masaeedu** [NetMQ/NetMQ.ReactiveExtensions#32]
I have a scenario where I'm trying to use multiple `PublisherNetMQ`s with an XSub endpoint. This doesn't work, since the PublisherNetMQ instance can't be configured to connect instead of binding. It would be great if the library respected the `@, >` indicators in the connection string as the main NetMQ library does.

**Comment by sharpe5** [comment]
I will accept pretty much any pull request if it solves a problem that you are encountering.

However, to be honest, this library is not really designed for many-to-many communications. It's realy designed for one-to-many communications, e.g. a service delivering data to one or more Excel plugin. You're better off with something like a custom ZeroMQ solution, or even RabbitMQ. The reason is that if you have many-to-many communication, you really need a stable broker to handle situations where participants come and go.
